server:
  port: 8080
  address: 127.0.0.1
  tomcat:
    uri-encoding: utf-8
  #context-path: /base
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: validate
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect

#视图层控制
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    static-path-pattern: /static/**
#mybatis
#实体类包
mybatis:
  typeAliasesPackage: com/wrdao/springboot/**/vo
#mapper.xml文件
  mapper-locations: classpath*:**/dao/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

#日志
logging:
  path: E:\idea\springbootdirdemo\log
  #level: info
  level:
       com.wrdao.spring.sys.dao : debug
  pattern:
    #console: "%d %logger %msg%n"
    file: "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"
  file:
    max-history: 10
    max-size: 4MB