server:
  port: 8080
  address: 127.0.0.1
  tomcat:
    uri-encoding: utf-8
  #context-path: /base
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: true

#视图层控制
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
  servlet:
    multipart:
      location: E:\files\
      max-file-size: -1
      max-request-size: -1
#mybatis
#实体类包
mybatis:
  typeAliasesPackage: com/wrdao/springboot/**/vo
#mapper.xml文件
  mapper-locations: classpath*:**/dao/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    cache-enabled: true #全局映射器启用缓存
    lazy-loading-enabled: false #查询时，关闭关联对象即时加载以提高性能
    use-column-label: true #允许使用列标签代替列名
    aggressive-lazy-loading: true #设置关联对象加载的形态，此处为按需加载字段(加载字段由SQL指定)，不会加载关联表的所有字段，以提高性能
    use-generated-keys: false #不允许使用自定义的主键值(比如由程序生成的UUID 32位编码作为键值)，数据表的PK生成策略将被覆盖
    local-cache-scope: session
#日志
logging:
  path: E:\idea\springbootdirdemo\log
  level:
    root : info
    com.wrdao.springboot.common : debug
    com.wrdao.springboot.configuration : debug
    com.wrdao.springboot.sys.dao : debug
    com.wrdao.springboot.file : debug
  pattern:
    #console: "%d %logger %msg%n"
    file: "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"
    #level: debug
  file:
    max-history: 10
    max-size: 4MB